### ISSUE TITLE
Unconcise naming

### ISSUE THREAD

**Issue by HilkopterBob** [HilkopterBob/TA#133]
![grafik](https://github.com/HilkopterBob/TA/assets/117028104/7030c0e1-6f8a-4333-a585-bed720b8ae0e)

shouldn't all attributes across the multiple item definitions should be named the same? why have some items desc as json, but the item-obj. still has dunder-slots and dunder-init description?

**Comment by Kartoffel096** [comment]
It should all be the same, desc was used after GECK Item Generator to quickly fix stuff.
Easy Fix -> Fix function in GECK so items get the description key not the desc key 
Longer Fix -> Change description to desc to shorten variable naming 

What do you prefer?
1 [ ]
2 [ ]

**Comment by HilkopterBob** [comment]
All desc

**Comment by Kartoffel096** [comment]
Consider that as WIP
